## This `docker-compose.yml` is used only for local development and tests. 

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory false"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    networks:
      - backend
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx512m"

  redis:
    image: redis:8.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    networks:
      - backend

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - backend

volumes:
  dynamodb-data:
    name: dynamodb_data
  redis-data:
    name: redis_data
  mongodb-data:
    name: mongodb_data
  mongodb-config:
    name: mongodb_config

networks:
  backend:
    name: backend_network
