service: belezeiro-iam
frameworkVersion: '4'

custom:
  eventBusName: !ImportValue belezeiro-${self:provider.stage}-event-bus-name
  eventBusArn: !ImportValue belezeiro-${self:provider.stage}-event-bus-arn

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: ${param:region, 'us-east-2'}
  stage: ${param:stage, 'dev'}

  httpApi:
    id: !ImportValue ${self:provider.stage}-BelezeiroHttpApiId

  eventBridge:
    useCloudFormation: true
    eventBus: ${self:custom.eventBusName}   # <--- agora o provider usa seu bus

  environment:
    STAGE: ${self:provider.stage}
    JWT_SECRET: ${env:JWT_SECRET}
    UPSTASH_REDIS_REST_URL: ${env:UPSTASH_REDIS_REST_URL}
    UPSTASH_REDIS_REST_TOKEN: ${env:UPSTASH_REDIS_REST_TOKEN}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:UpdateItem
          Resource:
            - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/belezeiro-${self:provider.stage}-main'
            - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/belezeiro-${self:provider.stage}-main/index/*'

        # Permissions to publish events to your EventBus (imported)
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource:
            - ${self:custom.eventBusArn}   # <--- AGORA SIM! IAM correto


functions:
  authenticate-user:
    handler: lambdas/authenticate-user.handler
    memorySize: 512
    timeout: 10
    events:
      - httpApi:
          path: /auth/authenticate-user
          method: POST
        
  get-me:
    handler: lambdas/get-me.handler
    memorySize: 512
    timeout: 10
    events:
      - httpApi:
          path: /auth/get-me
          method: GET

  create-user-permission-snapshot:
    handler: lambdas/create-user-permission-snapshot.handler
    memorySize: 512
    timeout: 10
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBusName}   # <--- ESSENCIAL!!
          pattern:
            source:
              - "iam-service"
            detail-type:
              - "iam.user.authenticated.v1"


build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    platform: node
    target: node20
    treeShaking: true
    keepNames: false
    format: cjs
    external:
      - aws-sdk
      - '@aws-sdk/client-dynamodb'
      - '@aws-sdk/lib-dynamodb'
      - '@aws-sdk/client-eventbridge'

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!**/*.test.ts'
    - '!**/*.spec.ts'
    - '!coverage/**'
    - '!tsconfig.json'
    - '!*.md'
    - '!*.config.*'
